### ISSUE TITLE
Connection cleanup without destroying socket

### ISSUE THREAD

**Issue by gfcittolin** [plcpeople/nodeS7#29]
We're having a pretty hard to solve issue on netsmarttech/node-red-contrib-s7#3. Some users of this Node-RED node are reporting that an uncaught exception related to the TCP connection is bringing the whole process down. I've already spent quite some hours trying to simulate it and I could **not** reproduce it. However, analyzing nodes7's code, I could find one special case where such a thing could happen.

In my previous experiences dealing with `net.Socket`, I found out it's only safe to remove all listeners from a socket after calling its `destroy()` method or after the `close` event, making sure that no more i/o operations will happen on it, [according to the docs](https://nodejs.org/api/net.html#net_socket_destroy_exception). 

On nodes7, however, all listeners are removed by calling `connectionCleanup()`, but `destroy()` is not called there. `destroy()` is only called on the *timeout* of `dropConnection()`, but `connectionCleanup()` is called from other places too, specially by `connectNow()`. Therefore, in some special cases, like packet timeouts, `connectNow()` may be called (and by consequence `connectionCleanup()`) **without** the previous connection being completely closed. This could lead to these strange exceptions being thrown.

Finally, I would like to suggest a modification: move the `destroy()` call to the `connectionCleanup()`, so we'd make sure we wouldn't left anything open before removing the listeners for errors. I hope this fixes or at least amends the problems there :)

Thanks!

**Comment by plcpeople** [comment]
OK I merged the PR.  

I saw a similar issue that I traced to the dropConnection function that I sort of fixed for an application of ours with commit "Fix for connection being cleaned up on client ending the connection" on Feb 27.  I solved a similar issue in my application, that doesn't have a dropConnection callback (which changes how this code runs) by using connectionReset() instead.  When you are having your issue is "onClientClose" being called?

One thing that helped me test this was popping the MMC card out of an S7-300 CPU which caused unexpected connection termination.  NodeS7 is supposed to handle this without crashing, and should re-establish connection when the MMC is put back in and running again.
