### ISSUE TITLE
Can I read variable by db name and variable name 

### ISSUE THREAD

**Issue by ishifman** [plcpeople/nodeS7#74]
Hi 
Thanks for the project
i need to acsess the variables via their names.
 
is it possible to read variable value by db and variable names?

for example 
if my DB named 'MyDb'
and the variable  DB name is 'VAR1'

can the  s7 Item's map can be assigned like this?

```
var variables = { TEST1: 'MyDb.VAR1' };   // Memory for variable 'VAR1' in 'MyDb' 
```

**Comment by gfcittolin** [comment]
Unfortunately, no. This library currently only supports addressing my memory area and address, and that's why you need to disable the "optimize block access" option in order to be able to access it from this here.

Having that said, there's an undergoing work to rewrite part of the library in early stage of development, that would allow this kind of feature. Get in touch if you could help on that.
