### ISSUE TITLE
Provide an example how to use this library

### ISSUE THREAD

**Issue by nagvenk** [plcpeople/nodeS7#95]
Can you please provide an example how to us eth is library

**Comment by ceremcem** [comment]
Did you see [README/Examples](https://github.com/plcpeople/nodeS7#examples)?

**Comment by ventr1x** [comment]
Many things are not documented and simply not tested at all.
For example a simple dropConnection() (which aparently is not used by the maintainer) is most of the time not enough and messes up the plugin entirely. I had to use connectionReset() and resetNow() on a simple Siemens plc to even disconnect correctly (it would block the plugin otherwise for whatever reason).
These functions are not documented. Any exposed function should be mentioned.

**Comment by nagvenk** [comment]
i am not working anymore on this
